name: one
description: An opinionated widgets & utilities library
version: 0.0.6
publish: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_image: ^4.1.11
  intl: any
  logging: ^1.2.0
  modal_bottom_sheet: ^3.0.0
  photo_view: ^0.15.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12

dev_dependencies:
  alchemist: ^0.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
