name: one
description: An opinionated widgets & utilities library
version: 0.0.6
publish: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_image: ^4.1.6
  intl: any
  logging: ^1.2.0
  modal_bottom_sheet: 3.0.0-pre
  photo_view: ^0.14.0
  shared_preferences: ^2.1.1
  shimmer: ^3.0.0
  sliver_tools: ^0.2.10

dev_dependencies:
  alchemist: ^0.6.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
