name: one
description: An opinionated widgets & utilities library
version: 0.0.5
publish: none

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_image: ^4.1.5
  http: ^0.13.5
  intl: ^0.17.0
  logging: ^1.1.1
  modal_bottom_sheet: 3.0.0-pre
  photo_view: ^0.14.0
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  sliver_tools: ^0.2.9

dev_dependencies:
  alchemist: ^0.5.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
